### PR TITLE
Fix typo in documentation

### LINKED ISSUE #146: Typo in documentation of function status?
In `src/client.rs`, for function `status`, the documentation is talking about `data_times`. But as I was unable to find `data_times` in the source code, I guess it is a typo and was meant to be `data_items`

### PR DESCRIPTION
**Pull request by Lem**
data_times should be data_items for
function "status"

Fixes #146

### CODE REVIEW

**Comment by jonhoo** [comment]
Hehe, looks like you made a typo too!

File: src/client.rs [hunk 1]
```diff
@@ -942,7 +942,7 @@ impl<T: Read + Write> Session<T> {
     ///  - `UIDVALIDITY`: The unique identifier validity value of the mailbox (see [`Uid`]).
     ///  - `UNSEEN`: The number of messages which do not have [`Flag::Seen`] set.
     ///
-    /// `data_times` is a space-separated list enclosed in parentheses.
+    /// `data_itmes` is a space-separated list enclosed in parentheses.
```
Comment (jonhoo) [inline src/client.rs]:
```suggestion
    /// `data_items` is a space-separated list enclosed in parentheses.
```

**Comment by Lem** [comment]
Yeah... Too much uptime for today to write in an foreign language :sleepy:
